var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/clients/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t2sco9._.js")
R.c("server/chunks/ssr/0.sk_0t~ua~v._.js")
R.c("server/chunks/ssr/0.sk_next_dist_esm_build_templates_app-page_0dvrl7d.js")
R.c("server/chunks/ssr/[root-of-the-server]__0td72~h._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0a5zn8_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ux0o96._.js")
R.c("server/chunks/ssr/0.sk_next_dist_client_components_0h0dhg2._.js")
R.c("server/chunks/ssr/0.sk_next_dist_client_components_builtin_forbidden_02.8hy1.js")
R.c("server/chunks/ssr/0.sk_next_dist_client_components_builtin_unauthorized_0..vh_4.js")
R.c("server/chunks/ssr/0.sk_next_dist_client_components_builtin_global-error_0qs.mcw.js")
R.c("server/chunks/ssr/0hoy_agency-dashboard__next-internal_server_app_clients_page_actions_0_8zcf2.js")
R.m(57775)
module.exports=R.m(57775).exports
